name: Command
main: Commands\Main
author: CrowBaldeYT
version: 1.1.2
api: 3.0.0
commands:
 nickoff:
  description: Disable Nick for You!
  usage: "/nickoff"
  permission: nick.cmd
 nick:
  description: set a Nick for You!
  usage: "/nick <text>"
  permission: nick.cmd
 heal:
   description: Heal yourself
   usage: "/heal"
   permission: heal.cmd
 feed:
   description: Feed yourself
   usage: "/feed"
   permission: feed.cmd
 clear:
   description: clear your inventory!
   aliases: ["clearinv", "ci"]
   usage: "/clear"
   permission: clear.cmd
 day:
   description: Set The Time to §e6000§r!
   usage: "/day"
   permission: day.cmd
 night:
   description: Set The Time to §e16000§r!
   usage: "/night"
   permission: night.cmd
